// APP
export const INIT = "app/INIT";

// LOADING
export const ADD_LOADING_ITEM = "loading/ADD_LOADING_ITEM";
export const REMOVE_LOADING_ITEM = "loading/REMOVE_LOADING_ITEM";

// ANALYTICS
export const GET_PRIMARY_LINE_DATA = "analytics/GET_PRIMARY_LINE_DATA";
export const GET_PRIMARY_LINE_DATA_SUCCESS =
  "analytics/GET_PRIMARY_LINE_DATA_SUCCESS";
export const GET_PRIMARY_LINE_DATA_FAIL =
  "analytics/GET_PRIMARY_LINE_DATA_FAIL";

export const GET_PRIMARY_BAR_DATA = "analytics/GET_PRIMARY_BAR_DATA";
export const GET_PRIMARY_BAR_DATA_SUCCESS =
  "analytics/GET_PRIMARY_BAR_DATA_SUCCESS";
export const GET_PRIMARY_BAR_DATA_FAIL = "analytics/GET_PRIMARY_BAR_DATA_FAIL";
